name: WhatsApp Auto Check

on:
  schedule:
    - cron: '*/5 * * * *'  # Her 5 dakikada bir
  workflow_dispatch:

jobs:
  whatsapp-check:
    runs-on: ubuntu-latest
    steps:
      - name: WhatsApp Kontrol
        run: |
          echo "$(date): WhatsApp kontrol başlatılıyor..."
          curl -s "http://phonegrafi.com/wap/cron/auto-control.php?cron=1"
          echo "$(date): Bitti"
